### PR TITLE
Automatic rock-release PR: integrate rc-patches in master

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by goldhoorn** [comment]
@D-Alex thougts?

**Comment by D-Alex** [comment]
I am just a bit puzzled why the problem was not triggered earlier. Furthermore, Fixnum is when also missing.

**Comment by goldhoorn** [comment]
Because the method gets refractored because of the spline problems and unneeded conversions.
Maybe you can provide a better patch which checks for subclasses?

**Comment by goldhoorn** [comment]
This got superseeded by #37

**Pull request merged**
