### PR TITLE
add a button to clear a plot

### PR DESCRIPTION
**Pull request by doudou**
Depends on:
- [ ] https://github.com/rock-core/gui-rock_widget_collection/pull/30

### CODE REVIEW

**Comment by doudou** [comment]
@renan028 could you have a look at this one (and the associated rock_widget_collection one)

**Comment by renan028** [comment]
Hi Sylvain,
it seems ok. How can I test it ? (load the test.ui and use the clear button)

**Comment by doudou** [comment]
> it seems ok. How can I test it ? (load the test.ui and use the clear button)

I just pushed an interactive test file in test/widgets/test_plot2d. Written some instructions in the README ... could you check it out and try ?

**Comment by renan028** [comment]
ok! I could test it and it worked.

**Pull request merged**
